[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmos-sdk-proto = "0.19.0"
cosmrs = "0.14.0"
hex = "0.4.3"
k256 = "0.13.3"
