[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
cosmos-sdk-proto = "0.19.0"
cosmrs = "0.14.0"
k256 = "0.13.3"
tendermint = "0.32.2"
